project:
  type: website
  output-dir: docs

website:
  title: "PSCI-3200"
  navbar:
    left:
      - href: Research Design.qmd
        text: Project Details

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



